from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setMinimumSize(QtCore.QSize(900, 650))
        MainWindow.resize(900, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.centralFrame = QtWidgets.QFrame(self.centralwidget)
        self.centralFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.centralFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.centralFrame.setObjectName("centralFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralFrame)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.leftFrame = QtWidgets.QFrame(self.centralFrame)
        self.leftFrame.setMinimumSize(QtCore.QSize(200, 471))
        self.leftFrame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.leftFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.leftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftFrame.setLineWidth(0)
        self.leftFrame.setObjectName("leftFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftFrame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.leftToolbarFrame = QtWidgets.QFrame(self.leftFrame)
        # self.leftToolbarFrame.setMinimumSize(QtCore.QSize(200, 369))
        self.leftToolbarFrame.setMinimumSize(QtCore.QSize(200, 414))
        self.leftToolbarFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftToolbarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftToolbarFrame.setObjectName("leftToolbarFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.leftToolbarFrame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2.addWidget(self.leftToolbarFrame)
        self.logoFrame = QtWidgets.QFrame(self.leftFrame)
        self.logoFrame.setMaximumSize(QtCore.QSize(16777215, 90))
        self.logoFrame.setStyleSheet("image: url(icons/femep-icon.png);")
        self.logoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logoFrame.setObjectName("logoFrame")
        self.verticalLayout_2.addWidget(self.logoFrame)
        self.horizontalLayout.addWidget(self.leftFrame)
        self.verticalLayout.addWidget(self.centralFrame)
        self.downToolbarFrame = QtWidgets.QFrame(self.centralwidget)
        self.downToolbarFrame.setMinimumSize(QtCore.QSize(865, 40))
        self.downToolbarFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.downToolbarFrame.setObjectName("downToolbarFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.downToolbarFrame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.downRightToolbarFrame = QtWidgets.QFrame(self.downToolbarFrame)
        self.downRightToolbarFrame.setObjectName("downRightToolbarFrame")
        self.lineXCoords = QtWidgets.QLineEdit(self.downRightToolbarFrame)
        self.lineXCoords.setEnabled(False)
        self.lineXCoords.setGeometry(QtCore.QRect(10, 10, 80, 20))
        self.lineXCoords.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineXCoords.setStyleSheet("color: rgb(0, 0, 0);")
        self.lineXCoords.setAlignment(QtCore.Qt.AlignCenter)
        self.lineXCoords.setObjectName("lineXCoords")
        self.lineYCoords = QtWidgets.QLineEdit(self.downRightToolbarFrame)
        self.lineYCoords.setEnabled(False)
        self.lineYCoords.setGeometry(QtCore.QRect(100, 10, 80, 20))
        self.lineYCoords.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineYCoords.setStyleSheet("color: rgb(0, 0, 0);")
        self.lineYCoords.setAlignment(QtCore.Qt.AlignCenter)
        self.lineYCoords.setObjectName("lineYCoords")
        self.horizontalLayout_3.addWidget(self.downRightToolbarFrame)
        self.downLeftToolbarFrame = QtWidgets.QFrame(self.downToolbarFrame)
        self.downLeftToolbarFrame.setMinimumSize(QtCore.QSize(200, 38))
        self.downLeftToolbarFrame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.downLeftToolbarFrame.setObjectName("downLeftToolbarFrame")

        self.snapcheckBox = QtWidgets.QCheckBox(self.downLeftToolbarFrame)
        self.snapcheckBox.setEnabled(True)
        self.snapcheckBox.setGeometry(QtCore.QRect(130, 10, 70, 20))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.snapcheckBox.sizePolicy().hasHeightForWidth())
        self.snapcheckBox.setSizePolicy(sizePolicy)
        self.snapcheckBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.snapcheckBox.setAcceptDrops(False)
        self.snapcheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.snapcheckBox.setAutoFillBackground(False)
        self.snapcheckBox.setStyleSheet("image: url(icons/Snap-to-grid.png);")
        self.snapcheckBox.setText("")
        self.snapcheckBox.setObjectName("snapcheckBox")

        # # Add control polygon checkbox
        # self.ctrlPolygonCheckBox = QtWidgets.QCheckBox(self.downLeftToolbarFrame)
        # self.ctrlPolygonCheckBox.setEnabled(True)
        # self.ctrlPolygonCheckBox.setGeometry(QtCore.QRect(60, 10, 70, 20))
        # sizePolicy = QtWidgets.QSizePolicy(
        #     QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(
        #     self.ctrlPolygonCheckBox.sizePolicy().hasHeightForWidth())
        # self.ctrlPolygonCheckBox.setSizePolicy(sizePolicy)
        # self.ctrlPolygonCheckBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        # self.ctrlPolygonCheckBox.setAcceptDrops(False)
        # self.ctrlPolygonCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        # self.ctrlPolygonCheckBox.setAutoFillBackground(False)
        # self.ctrlPolygonCheckBox.setStyleSheet("image: url(icons/ctrlpoly.png);")
        # self.ctrlPolygonCheckBox.setText("")
        # self.ctrlPolygonCheckBox.setObjectName("ctrlPolygonCheckBox")

        self.horizontalLayout_3.addWidget(self.downLeftToolbarFrame)
        self.verticalLayout.addWidget(self.downToolbarFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setStyleSheet("")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setAutoFillBackground(False)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setStyleSheet("")
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.secondToolBar = QtWidgets.QToolBar(MainWindow)
        self.secondToolBar.setStyleSheet("")
        self.secondToolBar.setObjectName("secondToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.secondToolBar)
        MainWindow.insertToolBarBreak(self.secondToolBar)
        self.modelingToolBar = QtWidgets.QToolBar(MainWindow)
        self.modelingToolBar.setStyleSheet("")
        self.modelingToolBar.setObjectName("modelingToolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.modelingToolBar)
        self.actionLine = QtWidgets.QAction(MainWindow)
        self.actionLine.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/Editing-Line-icon.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLine.setIcon(icon)
        self.actionLine.setObjectName("actionLine")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/openfile.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/savefile.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("icons/savefile.png"),
                         QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSaveAs.setIcon(icon21)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionExport = QtWidgets.QAction(MainWindow)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap("icons/export-icon.png"),
                         QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionExport.setIcon(icon30)
        self.actionExport.setObjectName("actionSaveAs")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/exit.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionExit.setIcon(icon3)
        self.actionExit.setObjectName("actionExit")
        self.actionFit = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/fit.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionFit.setIcon(icon4)
        self.actionFit.setObjectName("actionFit")
        self.actionZoomIn = QtWidgets.QAction(MainWindow)
        self.actionZoomIn.setCheckable(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/Zoomin.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionZoomIn.setIcon(icon5)
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.actionZoomOut = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/zoom-out.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionZoomOut.setIcon(icon6)
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.actionPanRight = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/pan-right.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPanRight.setIcon(icon7)
        self.actionPanRight.setObjectName("actionPanRight")
        self.actionPanLeft = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/pan-left.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPanLeft.setIcon(icon8)
        self.actionPanLeft.setObjectName("actionPanLeft")
        self.actionPanUp = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/pan-up.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPanUp.setIcon(icon9)
        self.actionPanUp.setObjectName("actionPanUp")
        self.actionPanDown = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/pan-down.png"),
                         QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPanDown.setIcon(icon10)
        self.actionPanDown.setObjectName("actionPanDown")
        self.actionGrid = QtWidgets.QAction(MainWindow)
        self.actionGrid.setCheckable(False)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(
            "icons/pattern_grid-35-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon11.addPixmap(QtGui.QPixmap("icons/grid.png"),
                         QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionGrid.setIcon(icon11)
        self.actionGrid.setObjectName("actionGrid")
        self.actionPolyline = QtWidgets.QAction(MainWindow)
        self.actionPolyline.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/polyline.png"),
                         QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPolyline.setIcon(icon12)
        self.actionPolyline.setObjectName("actionPolyline")

        self.actionCubicSpline = QtWidgets.QAction(MainWindow)
        self.actionCubicSpline.setCheckable(True)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("icons/cubicspline.png"),
                         QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCubicSpline.setIcon(icon21)
        self.actionCubicSpline.setObjectName("actionCubicSpline")

        self.actionCircle = QtWidgets.QAction(MainWindow)
        self.actionCircle.setCheckable(True)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("icons/circle.png"),
                         QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCircle.setIcon(icon22)
        self.actionCircle.setObjectName("actionCircle")

        self.actionCircleArc = QtWidgets.QAction(MainWindow)
        self.actionCircleArc.setCheckable(True)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("icons/circlearc.png"),
                         QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCircleArc.setIcon(icon23)
        self.actionCircleArc.setObjectName("actionCircleArc")

        self.actionEllipse = QtWidgets.QAction(MainWindow)
        self.actionEllipse.setCheckable(True)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap("icons/ellipse.png"),
                         QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionEllipse.setIcon(icon24)
        self.actionEllipse.setObjectName("actionEllipse")

        self.actionEllipseArc = QtWidgets.QAction(MainWindow)
        self.actionEllipseArc.setCheckable(True)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap("icons/ellipsearc.png"),
                         QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionEllipseArc.setIcon(icon25)
        self.actionEllipseArc.setObjectName("actionEllipseArc")

        self.actionDelete = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icons/delete-icon.png"),
                         QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon13.addPixmap(QtGui.QPixmap("icons/delete-icon.png"),
                         QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionDelete.setIcon(icon13)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSelect = QtWidgets.QAction(MainWindow)
        self.actionSelect.setCheckable(True)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(
            "icons/Cursor-Select-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSelect.setIcon(icon14)
        self.actionSelect.setObjectName("actionSelect")
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icons/new-file.png"),
                         QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon15.addPixmap(QtGui.QPixmap("icons/new-file.png"),
                         QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionNew.setIcon(icon15)
        self.actionNew.setObjectName("actionNew")
        self.actionCreatePatch = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("icons/patch.png"),
                         QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreatePatch.setIcon(icon16)
        self.actionCreatePatch.setObjectName("actionCreatePatch")
        self.actionPoint = QtWidgets.QAction(MainWindow)
        self.actionPoint.setCheckable(True)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("icons/point-icon.png"),
                         QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon17.addPixmap(QtGui.QPixmap("icons/point-icon.png"),
                         QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPoint.setIcon(icon17)
        self.actionPoint.setObjectName("actionPoint")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("icons/undo-icon.png"),
                         QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon18)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("icons/redo-icon.png"),
                         QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon19)
        self.actionAttmanager = QtWidgets.QAction(MainWindow)
        self.actionAttmanager.setCheckable(True)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("icons/att-icon.png"),
                         QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAttmanager.setIcon(icon20)
        self.actionAttmanager.setObjectName("actionAttmanager")
        self.actionRedo.setObjectName("actionRedo")
        self.actionNsudv = QtWidgets.QAction(MainWindow)
        self.actionNsudv.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/nsudv-icon.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNsudv.setIcon(icon)
        self.actionNsudv.setObjectName("actionNsudv")
        self.actionMesh = QtWidgets.QAction(MainWindow)
        self.actionMesh.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/mesh.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMesh.setIcon(icon)
        self.actionMesh.setObjectName("actionMesh")

        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.mainToolBar.addAction(self.actionNew)
        self.mainToolBar.addAction(self.actionOpen)
        self.mainToolBar.addAction(self.actionSave)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionUndo)
        self.mainToolBar.addAction(self.actionRedo)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionFit)
        self.mainToolBar.addAction(self.actionZoomIn)
        self.mainToolBar.addAction(self.actionZoomOut)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionPanLeft)
        self.mainToolBar.addAction(self.actionPanRight)
        self.mainToolBar.addAction(self.actionPanUp)
        self.mainToolBar.addAction(self.actionPanDown)
        self.secondToolBar.addAction(self.actionSelect)
        self.secondToolBar.addAction(self.actionDelete)
        self.secondToolBar.addSeparator()
        self.secondToolBar.addAction(self.actionGrid)
        self.secondToolBar.addAction(self.actionAttmanager)
        self.secondToolBar.addAction(self.actionNsudv)
        self.secondToolBar.addAction(self.actionMesh)
        self.modelingToolBar.addAction(self.actionPoint)
        self.modelingToolBar.addAction(self.actionLine)
        self.modelingToolBar.addAction(self.actionPolyline)
        self.modelingToolBar.addAction(self.actionCubicSpline)
        self.modelingToolBar.addAction(self.actionCircle)
        self.modelingToolBar.addAction(self.actionCircleArc)
        self.modelingToolBar.addAction(self.actionEllipse)
        self.modelingToolBar.addAction(self.actionEllipseArc)
        self.modelingToolBar.addSeparator()
        self.modelingToolBar.addAction(self.actionCreatePatch)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "FEMEP - Finite Element Method Educational Computer Program"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.mainToolBar.setWindowTitle(
            _translate("MainWindow", "mainToolBar"))
        self.secondToolBar.setWindowTitle(
            _translate("MainWindow", "secondToolBar"))
        self.modelingToolBar.setWindowTitle(
            _translate("MainWindow", "modelingToolBar"))
        self.actionLine.setText(_translate("MainWindow", "Line"))
        self.actionLine.setToolTip(_translate("MainWindow", "Line (L)"))
        self.actionLine.setShortcut(_translate("MainWindow", "L"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setToolTip(_translate(
            "MainWindow", "Open File (Ctrl + O)"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setToolTip(_translate(
            "MainWindow", "Save File (Ctrl + S)"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save as"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionFit.setText(_translate("MainWindow", "Fit"))
        self.actionFit.setToolTip(_translate("MainWindow", "Fit (F)"))
        self.actionFit.setShortcut(_translate("MainWindow", "F"))
        self.actionZoomIn.setText(_translate("MainWindow", "ZoomIn"))
        self.actionZoomIn.setToolTip(_translate("MainWindow", "ZoomIn"))
        self.actionZoomOut.setText(_translate("MainWindow", "ZoomOut"))
        self.actionZoomOut.setToolTip(_translate("MainWindow", "ZoomOut"))
        self.actionPanRight.setText(_translate("MainWindow", "PanRight"))
        self.actionPanRight.setToolTip(_translate("MainWindow", "PanRight"))
        self.actionPanRight.setShortcut(_translate("MainWindow", "Right"))
        self.actionPanLeft.setText(_translate("MainWindow", "PanLeft"))
        self.actionPanLeft.setToolTip(_translate("MainWindow", "PanLeft"))
        self.actionPanLeft.setShortcut(_translate("MainWindow", "Left"))
        self.actionPanUp.setText(_translate("MainWindow", "PanUp"))
        self.actionPanUp.setToolTip(_translate("MainWindow", "PanUp"))
        self.actionPanUp.setShortcut(_translate("MainWindow", "Up"))
        self.actionPanDown.setText(_translate("MainWindow", "PanDown"))
        self.actionPanDown.setToolTip(_translate("MainWindow", "PanDown"))
        self.actionPanDown.setShortcut(_translate("MainWindow", "Down"))
        self.actionGrid.setText(_translate("MainWindow", "Grid"))
        self.actionGrid.setToolTip(_translate("MainWindow", "Set Grid (G)"))
        self.actionGrid.setShortcut(_translate("MainWindow", "G"))
        self.actionPolyline.setText(_translate("MainWindow", "Polyline"))
        self.actionPolyline.setToolTip(_translate(
            "MainWindow", "Polyline (Shift + P)"))
        self.actionPolyline.setShortcut(_translate("MainWindow", "Shift+P"))

        self.actionCubicSpline.setText(_translate("MainWindow", "CubicSpline"))
        self.actionCubicSpline.setToolTip(_translate(
            "MainWindow", "CubicSpline (Shift + S)"))
        self.actionCubicSpline.setShortcut(_translate("MainWindow", "Shift + S"))

        self.actionCircle.setText(_translate("MainWindow", "Circle"))
        self.actionCircle.setToolTip(_translate(
            "MainWindow", "Circle (C)"))
        self.actionCircle.setShortcut(_translate("MainWindow", "C"))

        self.actionCircleArc.setText(_translate("MainWindow", "CircleArc"))
        self.actionCircleArc.setToolTip(_translate(
            "MainWindow", "CircleArc (Shift + C)"))
        self.actionCircleArc.setShortcut(_translate("MainWindow", "Shift+C"))

        self.actionEllipse.setText(_translate("MainWindow", "Ellipse"))
        self.actionEllipse.setToolTip(_translate(
            "MainWindow", "Ellipse (E)"))
        self.actionEllipse.setShortcut(_translate("MainWindow", "E"))

        self.actionEllipseArc.setText(_translate("MainWindow", "EllipseArc"))
        self.actionEllipseArc.setToolTip(_translate(
            "MainWindow", "EllipseArc (Shift + E)"))
        self.actionEllipseArc.setShortcut(_translate("MainWindow", "Shift+E"))

        self.actionDelete.setText(_translate("MainWindow", "Delete (Del)"))
        self.actionDelete.setShortcut(_translate("MainWindow", "Del"))
        self.actionSelect.setText(_translate("MainWindow", "Select"))
        self.actionSelect.setToolTip(_translate("MainWindow", "Select (S)"))
        self.actionSelect.setShortcut(_translate("MainWindow", "S"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setToolTip(_translate(
            "MainWindow", "New File (Ctrl + N)"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionCreatePatch.setText(
            _translate("MainWindow", "CreatePatch"))
        self.actionCreatePatch.setToolTip(
            _translate("MainWindow", "Create Patch "))
        self.actionPoint.setText(_translate("MainWindow", "Point"))
        self.actionPoint.setToolTip(_translate("MainWindow", "Point (P)"))
        self.actionPoint.setShortcut(_translate("MainWindow", "P"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setToolTip(_translate("MainWindow", "Undo (Ctrl + Z)"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setToolTip(_translate("MainWindow", "Redo (Ctrl + Y)"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionAttmanager.setToolTip(
            _translate("MainWindow", "Attribute Manager"))
        self.actionMesh.setToolTip(_translate("MainWindow", "Mesh Manager"))
        self.actionNsudv.setToolTip(_translate(
            "MainWindow", "Number of Subdivisions"))
